### ISSUE TITLE
Can create a broken wire:

### ISSUE THREAD

**Issue by Carter12s** [GGBRW/BOOLR#19]
I can create a broken wire which appears to no longer carry signal. To reproduce:

1. Place a clock
2. Place a Counter (I'm calling this A)
3. Place a second Counter (I'm Calling this B)
4. Connect the clock to counter A
5. Connect Counter B to the a middle section of wire
![image](https://user-images.githubusercontent.com/8097919/31690679-ad38fe74-b350-11e7-9023-80047d5abb26.png)

6. Create a loop in the wire connecting Counter B back the wire between the clock and A. 
![image](https://user-images.githubusercontent.com/8097919/31690691-bbd79dfa-b350-11e7-8e86-bc2e140faa56.png)

The wire is now broken, and neither counter will update. 

V1.0.3 Windows

**Comment by painballking** [comment]
May be important to note that the bug only occurs when the last connection is made while the clock is sending a signal to the lines.
