### ISSUE TITLE
Version for touch screens

### ISSUE THREAD

**Issue by IlyaPetrovM** [GGBRW/BOOLR#33]
Hi! will you add the touch screen support with two finger functionality (for zooming)?

**Comment by ghost** [comment]
I made a pull request with initial touchscreen support. You can wait till it's merged or try it out over on my branch. No executable is provided only source code but I can give you instructions on how to build it for your system if u want (not that complicated). If there are any missing touchscreen features or any bugs, please let me know and I'll try my best to fix them as soon as possible
Dreamer

**Comment by IlyaPetrovM** [comment]
It's nice to see that! 
I would be happy with your instructions for compiling the project for Windows (64bit).

**Comment by ghost** [comment]
I will not provide a build because I think it's not secure if you just provide an executable with no sources. So I decided to make an instruction on my repository on how to "build" it. If you follow that you will easily build your own touchscreen supported BOOLR.

**Comment by ghost** [comment]
oops, forgot to give a link: [my repo](https://github.com/dreamerplays/boolr)
Dreamer

**Comment by ghost** [comment]
Can u let me know if it is working? Are you missing any features? Would be awesome to hear some feedback

**Comment by IlyaPetrovM** [comment]
Yes! It works at all, but there is an issue with moving the elements.

**Comment by ghost** [comment]
Thanks, I will take a look at it. Can u tell me in what scenario the issue happens so I can troubleshoot it better?
Dreamer

**Comment by IlyaPetrovM** [comment]
What is scenario? 
I can't move every element I've created on the board.

**Comment by ghost** [comment]
A scenario is a certain development of events . Like for example: a possible scenario is that he got attacked after opening the door. That's a scenario. Thanks for the help, I'll have a look what causes that behavior
Dreamer

**Comment by ghost** [comment]
So I made a new release 1.1.1 that addressed a bug where you can't move a component after closing the context menu. Is this the bug you mean or is it a different one? If it's not the one you meant please give me advice on how to reproduce it so I can investigate.
Dreamer

**Comment by IlyaPetrovM** [comment]
I understood that I have to use ``Ctrl`` key to move elements. I checked this in your first release. 
I use Boolr with sensor blackboard with keyboard, so this method for moving elements is OK.

**Comment by ghost** [comment]
So does everything work now? I will soon make 2 buttons in the bottom right so nobody has to use a keyboard. Like a little switch😉
Dreamer

**Comment by IlyaPetrovM** [comment]
Nice!
Thank you!

**Comment by ghost** [comment]
Updates are now coming at https://github.com/LightCubeD/BOOLR
