### ISSUE TITLE
Add a tri-state buffer (and a logic analyzer/oscillator)

### ISSUE THREAD

**Issue by cytesys** [GGBRW/BOOLR#34]
A tri-state buffer would be a nice addition to BOOLR. Also, some kind of a virtual logic analyzer or oscillator would be great! :electron: 😄

**Comment by yasharAhari** [comment]
The BOOLR does not stimulate the electrical part, thus two outputs can connect to a same wire with no problem. No short circuit, No need for tri-state buffer. However, I would like to see those components in 
the future updates.
