### ISSUE TITLE
macOs Catalina

### ISSUE THREAD

**Issue by JentlSuy** [GGBRW/BOOLR#47]
Unable to create a new project on macOS Catalina

**Comment by KenjutsuGH** [comment]
After typing in a board name, such as test.board, and clicking on "Create" nothing happens.

macOS High Sierra 10.13.6

**Comment by ghost** [comment]
Seeing the same.

**Comment by sam-centrevilletech** [comment]
Same issue but on Windows

**Comment by beddy70** [comment]
I found how start : 

On the finder with right mouse button open package et go in folder : 

Contents/MacOS and double click on file BOOLR. You can create project when you launch with this way.
