### ISSUE TITLE
A solution proposal...

### ISSUE THREAD

**Issue by Heliex** [GGBRW/BOOLR#65]
Hello !

I'd know if this project is dead ? some PR are really old and still not merged in the main branch...Anyway i'd like to propose a solution to make this project alive again : 

I've worked this evening to redo all commit that people asked to merge in the main branch, if you want to see these, you can go to the fork on my repository.

Here are all the PR that i did redo : 

- PR#54 - SR LATCH
- PR#55 - D LATCH
- PR#56 - FLIP FLOP
- PR#26 - NOR, XNOR, NAND GATES AS BASIC GATES

Here all all the PR that i did not redo :

- PR#53 - ADD LED ARRAY
- PR#52 - FIX WIRE BUGS
- PR#51 - BUMP ELECTRON 1.8.8 to 9.1.0

> Electron dependencies has been upgrade from 1.8.8 to 17.1.0 (That's why i didn't redo the PR#51)

I've also made a new version of the tool ready to use via electron-build that you can get from my forked repository.
Let's revive this wonderful tool together  ! I'm suggesting you to go to my forked repository and open issues.

Have a good night/day my fellow developpers !

**Comment by KostyaCholak** [comment]
Sounds great! Hope maintainers will support this.
I contacted them (gees@ggbrw.nl and confiks@scriptbase.org) on Sep 13, 2020, but didn't get an answer.

**Comment by Heliex** [comment]
Hello @KostyaCholak ,

Since none has given an answer to you, are you interested in the fact that i redo the PR#53 ad PR#52 in my fork ?

We could then try to start a new features/bug corrections set for the up-to-date version of the tool.
I'd like to reorganize the code as a class oriented/separated in the folder (better structure and more clarity) for more maintainability and flexibility, what do you think about it ?

**Comment by KostyaCholak** [comment]
Sure, feel free to redo them. I don't have as much time now (plus there is war in my country for the last two weeks), so I'm not sure I can help a lot, but I would be glad to.

**Comment by Heliex** [comment]
Well, thanks for you return

I send you all my supports for this uncertain moment you're going through (and expect this war to stop as soon as possible in the best way as possible). My best's wishes for you. 

I close this issue for now and i'll tag you again for the next improvments directly in my repository.

**Comment by KostyaCholak** [comment]
Thanks @Heliex !
